import type { ActivityEvent, AdminNotification } from "./ops-types";

export const seedActivity: ActivityEvent[] = [
  {
    id: "act-001",
    actorName: "نورة الحنّاء",
    actorId: "user-noura",
    action: "تحديث حالة طلب",
    target: "ORD-2026-00125",
    entityType: "order",
    entityId: "ORD-2026-00125",
    before: "بانتظار الدفع",
    after: "جاري مراجعة",
    createdAt: "2026-09-11T05:12:00.000Z",
    meta: "بانتظار الدفع → جاري مراجعة",
    ip: "185.12.44.18",
  },
  {
    id: "act-002",
    actorName: "أحمد العمليات",
    actorId: "user-ahmed",
    action: "تعديل مخزون منتج",
    target: "تاج العروس الملكي",
    entityType: "product",
    entityId: "prod-002",
    before: "8",
    after: "12",
    createdAt: "2026-09-11T04:40:00.000Z",
    meta: "المخزون: 8 → 12",
    ip: "185.12.44.22",
  },
  {
    id: "act-003",
    actorName: "محمد باغووبير",
    actorId: "user-mohammed",
    action: "إنشاء مستخدم",
    target: "عمر الدعم",
    entityType: "user",
    entityId: "user-omar",
    after: "دور: تشغيل · نشط",
    createdAt: "2026-09-10T18:05:00.000Z",
    meta: "دور: تشغيل",
    ip: "185.12.40.9",
  },
  {
    id: "act-004",
    actorName: "ريم التسويق",
    actorId: "user-reem",
    action: "تفعيل عرض",
    target: "عروض العروس",
    entityType: "offer",
    entityId: "offer-bridal",
    before: "معطّل",
    after: "نشط",
    createdAt: "2026-09-10T16:22:00.000Z",
    ip: "185.12.51.3",
  },
  {
    id: "act-005",
    actorName: "أحمد العمليات",
    actorId: "user-ahmed",
    action: "تحديث حالة طلب",
    target: "ORD-2026-00118",
    entityType: "order",
    entityId: "ORD-2026-00118",
    before: "جاري التجهيز",
    after: "تم التسليم",
    createdAt: "2026-09-10T14:10:00.000Z",
    meta: "جاري التجهيز → تم التسليم",
    ip: "185.12.44.22",
  },
  {
    id: "act-006",
    actorName: "نورة الحنّاء",
    actorId: "user-noura",
    action: "تعديل إعدادات المتجر",
    target: "واتساب + التوصيل",
    entityType: "settings",
    entityId: "store-settings",
    before: "أيام: 3–7",
    after: "أيام: 2–5",
    createdAt: "2026-09-10T11:30:00.000Z",
    meta: "تحديث رقم الواتساب ومدة التوصيل",
    ip: "185.12.44.18",
  },
  {
    id: "act-007",
    actorName: "خالد المخزن",
    actorId: "user-khaled",
    action: "تعطيل منتج",
    target: "نقشة يومية ناعمة",
    entityType: "product",
    entityId: "prod-010",
    before: "نشط",
    after: "معطّل",
    createdAt: "2026-09-09T20:15:00.000Z",
    ip: "185.12.33.11",
  },
  {
    id: "act-008",
    actorName: "محمد باغووبير",
    actorId: "user-mohammed",
    action: "تعديل صلاحيات دور",
    target: "تشغيل",
    entityType: "role",
    entityId: "role-ops",
    before: "بدون customers.view",
    after: "مع customers.view",
    createdAt: "2026-09-09T09:00:00.000Z",
    meta: "إضافة customers.view",
    ip: "185.12.40.9",
  },
  {
    id: "act-009",
    actorName: "أحمد العمليات",
    actorId: "user-ahmed",
    action: "تعديل قسم",
    target: "نقشات اليد",
    entityType: "category",
    entityId: "cat-hand",
    createdAt: "2026-09-08T15:45:00.000Z",
    ip: "185.12.44.22",
  },
  {
    id: "act-010",
    actorName: "نورة الحنّاء",
    actorId: "user-noura",
    action: "تسجيل دخول",
    target: "لوحة الإدارة",
    entityType: "auth",
    entityId: "session",
    createdAt: "2026-09-08T08:02:00.000Z",
    ip: "185.12.44.18",
  },
  {
    id: "act-011",
    actorName: "ريم التسويق",
    actorId: "user-reem",
    action: "رفع وسائط منتج",
    target: "نقشة الياسمين الذهبي",
    entityType: "media",
    entityId: "prod-001",
    after: "صورتان + فيديو قصير",
    createdAt: "2026-09-07T19:20:00.000Z",
    ip: "185.12.51.3",
  },
  {
    id: "act-012",
    actorName: "أحمد العمليات",
    actorId: "user-ahmed",
    action: "تسجيل خروج",
    target: "لوحة الإدارة",
    entityType: "auth",
    entityId: "session",
    createdAt: "2026-09-07T16:00:00.000Z",
    ip: "185.12.44.22",
  },
];

export const seedNotifications: AdminNotification[] = [
  {
    id: "ntf-001",
    title: "طلب بانتظار الدفع",
    body: "ORD-2026-00125 بحاجة لمراجعة إيصال التحويل البنكي",
    createdAt: "2026-09-11T05:15:00.000Z",
    read: false,
    href: "/admin/orders",
    type: "payment",
  },
  {
    id: "ntf-002",
    title: "مخزون منخفض",
    body: "منتجات وصلت لحد الكمية المنخفضة — راجعي قائمة المنتجات",
    createdAt: "2026-09-11T04:00:00.000Z",
    read: false,
    href: "/admin/products?stock=low_stock",
    type: "stock",
  },
  {
    id: "ntf-003",
    title: "طلب جديد",
    body: "وصل طلب جديد من عميلة عبر المتجر",
    createdAt: "2026-09-10T19:30:00.000Z",
    read: false,
    href: "/admin/orders",
    type: "order",
  },
  {
    id: "ntf-004",
    title: "تذكير إعدادات واتساب",
    body: "تأكدي من رقم واتساب إرسال الإيصالات في الإعدادات",
    createdAt: "2026-09-10T10:00:00.000Z",
    read: true,
    href: "/admin/settings",
    type: "system",
  },
  {
    id: "ntf-005",
    title: "عرض ينتهي قريبًا",
    body: "حملة عروض قد تقترب من تاريخ الانتهاء",
    createdAt: "2026-09-09T14:00:00.000Z",
    read: true,
    href: "/admin/offers",
    type: "system",
  },
];
